import { test, expect } from '@playwright/test';

test.describe( 'Course Management', () => {
	test.setTimeout( 120000 ); // Increase timeout for slow environments

	test( 'should act as admin, create a new course, publish it, and verify it on frontend', async ( {
		page,
	} ) => {
		// 1. Login
		await page.goto( '/wp-admin/post-new.php?post_type=dos_service' );

		// Handle login if redirected
		if ( page.url().includes( 'wp-login.php' ) ) {
			await page.fill(
				'#user_login',
				process.env.WP_USERNAME || 'admin'
			);
			await page.fill(
				'#user_pass',
				process.env.WP_PASSWORD || 'password'
			);
			await page.click( '#wp-submit' );
			await page.waitForURL( /\/wp-admin\// );
			await page.goto( '/wp-admin/post-new.php?post_type=dos_service' );
		}

		// 2. Fill Course Title and Content
		const courseTitle = 'E2E Test Course ' + Date.now();
		const courseContent =
			'This is a test course description generated by Playwright.';

		// Wait for editor to fully load
		await page.waitForLoadState( 'domcontentloaded' );

		// Try to find the title area.
		// We use a broader timeout here as initial editor load can be slow.
		try {
			const titleLocator = page.getByRole( 'textbox', {
				name: 'Add title',
			} );
			await titleLocator.waitFor( { state: 'visible', timeout: 30000 } );
			await titleLocator.fill( courseTitle );
		} catch ( e ) {
			// Fallback for older WP versions or different editor states
			await page.fill( '.editor-post-title__input', courseTitle );
		}

		// Content step
		// We can click the block appender or finding the first paragraph block
		// Try clicking the default appender
		try {
			await page
				.locator( '.block-editor-default-block-appender' )
				.click( { timeout: 5000 } );
		} catch ( e ) {
			// Fallback - maybe click the first block area
			await page
				.locator( '.wp-block-post-content' )
				.click( { timeout: 5000 } )
				.catch( () => {} );
		}
		await page.keyboard.type( courseContent );

		// 3. Publish
		// Click Publish button (top right)
		// Ensure we find the main "Publish" or "Submit for Review" button
		const topPublishButton = page
			.getByRole( 'button', { name: 'Publish', exact: true } )
			.or( page.getByRole( 'button', { name: 'Update' } ) );
		await topPublishButton.waitFor();
		await topPublishButton.click();

		// Click final Publish confirmation (the side panel), if it appears
		try {
			const panelPublishButton = page.locator(
				'.editor-post-publish-panel__header .editor-post-publish-button'
			);
			if ( await panelPublishButton.isVisible( { timeout: 5000 } ) ) {
				await panelPublishButton.click();
			}
		} catch ( e ) {
			// Probably already published or no double-confirm needed
		}

		// 4. Verify Success Message
		// Snackbar says "Post published." or similar.
		const snackbar = page.locator( '.components-snackbar' );
		await expect( snackbar ).toContainText( /published|updated/i );

		// 5. Visit Frontend
		const viewPostLink = snackbar.getByRole( 'link', {
			name: 'View Post',
		} );

		// wait for it
		if ( await viewPostLink.isVisible() ) {
			const [ newPage ] = await Promise.all( [
				page.context().waitForEvent( 'page' ),
				viewPostLink.click(),
			] );
			await newPage.waitForLoadState( 'domcontentloaded' );

			// Verify Title and Content
			await expect( newPage.locator( 'h1' ) ).toContainText(
				courseTitle
			);
			await expect( newPage.locator( 'body' ) ).toContainText(
				courseContent
			);
		}
	} );
} );
